"use client";

import React, { useEffect } from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import Provider from './Provider';
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs';
import Head from 'next/head';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  useEffect(() => {
    // Nettoyer les attributs non désirés
    const cleanAttributes = (element) => {
      element.removeAttribute('data-new-gr-c-s-check-loaded');
      element.removeAttribute('data-gr-ext-installed');
    };

    const body = document.querySelector('body');
    const html = document.querySelector('html');
    if (body) cleanAttributes(body);
    if (html) cleanAttributes(html);
  }, []);

  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>StudyAbroad</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <body className={inter.className}>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          <Provider>
              <Toaster />
              {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
